"""Configuration météo centralisée, pilotée par variables d'environnement."""
from __future__ import annotations
import os

WEATHER_CACHE_TTL_SECONDS = int(os.getenv("WEATHER_CACHE_TTL_SECONDS", "180"))
WEATHER_HISTORY_SIZE = int(os.getenv("WEATHER_HISTORY_SIZE", "5"))
WEATHER_PARALLEL_WORKERS = int(os.getenv("WEATHER_PARALLEL_WORKERS", "4"))
WEATHER_SKIP_PAST_COMPLETED = os.getenv("WEATHER_SKIP_PAST_COMPLETED", "1") not in {"0", "false", "False"}

WEATHER_PROVIDER_MAX_FORECAST_HOURS = int(os.getenv("WEATHER_PROVIDER_MAX_FORECAST_HOURS", "168"))
WEATHER_LONG_RANGE_MAX_HOURS = 30 * 24
WEATHER_PLANNING_MAX_HOURS = 7 * 24
WEATHER_TACTICAL_MAX_HOURS = 24
WEATHER_OPERATIONAL_MAX_HOURS = 2

WEATHER_REFRESH_STRATEGIC_SECONDS = int(os.getenv("WEATHER_REFRESH_STRATEGIC_SECONDS", str(6 * 3600)))
WEATHER_REFRESH_PLANNING_SECONDS = int(os.getenv("WEATHER_REFRESH_PLANNING_SECONDS", str(60 * 60)))
WEATHER_REFRESH_TACTICAL_SECONDS = int(os.getenv("WEATHER_REFRESH_TACTICAL_SECONDS", str(10 * 60)))
WEATHER_REFRESH_OPERATIONAL_SECONDS = int(os.getenv("WEATHER_REFRESH_OPERATIONAL_SECONDS", "60"))

WEATHER_MONITOR_THRESHOLD = float(os.getenv("WEATHER_MONITOR_THRESHOLD", "0.45"))
WEATHER_DELAY_THRESHOLD = float(os.getenv("WEATHER_DELAY_THRESHOLD", "0.70"))
WEATHER_SEVERE_THRESHOLD = float(os.getenv("WEATHER_SEVERE_THRESHOLD", "0.85"))
WEATHER_EXTREME_THRESHOLD = float(os.getenv("WEATHER_EXTREME_THRESHOLD", "0.92"))
PERSISTENCE_SAMPLE_COUNT = int(os.getenv("WEATHER_PERSISTENCE_SAMPLE_COUNT", "3"))
