stages:
  - build

frontend:
  stage: build
  image: node:20-alpine
  script:
    - cd airline-scheduling-front
    - npm install
    - npx vite build
  only:
    - main
    - master
    - merge_requests

backend:
  stage: build
  image: node:20-alpine
  script:
    - cd airline-scheduling-back/back-airline-scheduling
    - npm install
    - npm run build
  only:
    - main
    - master
    - merge_requests

ai-module:
  stage: build
  image: nikolaik/python-nodejs:python3.10-nodejs20-slim
  script:
    - cd airline-ia
    - |
      if [ -f package.json ]; then
        echo "-> Verification compilation Node.js pour airline-ia..."
        npm install
        npm run build --if-present
      elif [ -f requirements.txt ]; then
        echo "-> Verification de la syntaxe Python pour airline-ia..."
        pip install --upgrade pip
        pip install -r requirements.txt
        python -m compileall .
      else
        echo "-> Aucun package.json ni requirements.txt trouve dans airline-ia."
      fi
  only:
    - main
    - master
    - merge_requests