name: Pipeline CI - Verification et Compilation

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

# Annule automatiquement les builds obsolètes si ussé
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # -------------------------------------------------------------
  # 1. Verification Compilation Frontend (React)
  # -------------------------------------------------------------
  frontend:
    name: Compilation Frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: airline-scheduling-front

    steps:
      - name: Récupération du code
        uses: actions/checkout@v4

      - name: Configuration Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Installation dépendances
        run: npm install

      - name: Test de compilation Web (Vite)
        run: npx vite build

  # -------------------------------------------------------------
  # 2. Verification Compilation Backend (NestJS)
  # -------------------------------------------------------------
  backend:
    name: Compilation Backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: airline-scheduling-back/back-airline-scheduling

    steps:
      - name: Récupération du code
        uses: actions/checkout@v4

      - name: Configuration Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Installation dépendances
        run: npm install

      - name: Test de compilation TypeScript (NestJS)
        run: npm run build

  # -------------------------------------------------------------
  # 3. Verification Syntaxe Module IA (Python / Node)
  # -------------------------------------------------------------
  ai-module:
    name: Verification Module IA
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: airline-ia

    steps:
      - name: Récupération du code
        uses: actions/checkout@v4

      - name: Configuration Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Configuration Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Verification de la syntaxe
        run: |
          if [ -f package.json ]; then
            echo "-> Verification compilation Node.js pour airline-ia..."
            npm install
            npm run build --if-present
          elif [ -f requirements.txt ]; then
            echo "-> Verification de la syntaxe Python pour airline-ia..."
            pip install --upgrade pip
            pip install -r requirements.txt
            python -m compileall .
          else
            echo "-> Aucun package.json ni requirements.txt trouve dans airline-ia."
          fi